config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items
  end
  root to: 'pages#index'
  controller :pages do
    get :test
    get :another_test
    get :to_do_list
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items, :dependent => :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end

  def test
    @messages = %w[Testing\ vue\ world Next\ line And\ one\ more\ here]
  end

  def another_test; end

  def to_do_list

  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /todo_items or /todo_items.json
  def index
    todolist = TodoList.find params[:todo_list_id]
    @todo_items = todolist.todo_items
  end

  # GET /todo_items/1 or /todo_items/1.json
  def show
    todolist = TodoList.find params[:todo_list_id]
    @todo_items = todolist.todo_items
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items or /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

      if @todo_item.save
        render json: @todo_item
      else
        render json: { errors: @todo_item.errors }, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /todo_items/1 or /todo_items/1.json
  def update
    if @todo_item.update(todo_item_params)
        render json: @todo_item
      else
        render json: { errors: @todo_item.errors }, status: :unprocessable_entity
      end
  end

  # DELETE /todo_items/1 or /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: "Todo item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_item_params
      params.require(:todo_item).permit(:name, :details, :completed, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1 or /todo_lists/1.json
  def show
    todolist = TodoList.find params[:id]
    @todo_items = todolist.todo_items
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists or /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    if @todo_list.save
      render json: @todo_list
    else
      render json: @todo_list.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    if @todo_list.update(todo_list_params)
      render json: @todo_list
    else
      render json: { json: @todo_lists.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: "Todo list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vue3Tailwind2Rails6121Ruby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_packs_with_chunks_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="w-3/5 max-w-full mx-auto mb-20 mt-10" data-behavior="vue">
      <div class="mb-10 text-lg space-x-5">
        <a class="text-gray-600 hover:underline hover:text-light-blue-700" href="/">Home</a>
        <span>/</span>
        <a class="text-gray-600 hover:underline hover:text-light-blue-700" href="<%= test_path %>">Test</a>
        <span>/</span>
        <a class="text-gray-600 hover:underline hover:text-light-blue-700" href="<%= another_test_path %>">Another Test</a>
        <span>/</span>
        <a class="text-gray-600 hover:underline hover:text-light-blue-700" href="<%= todo_lists_path %>">To Do List</a>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/another_test.html.erb
<v-another-test></v-another-test>

app/views/pages/index.html.erb
<h1 class="pb-4 text-3xl">Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<div class="p-10 text-9xl text-purple-500 font-bold my-10">
  <v-hello-world></v-hello-world>
</div>
<v-test message="Testing both"></v-test>

app/views/pages/test.html.erb
<h1 class="pb-4 text-3xl">Pages#test</h1>
<p>Find me in app/views/pages/test.html.erb</p>

<div class="flex-col inline-flex space-y-4 mt-20">
  <v-test v-for="(message, index) in <%= @messages.to_json %>" :key="index" :message="message"></v-test>
</div>

app/views/pages/to_do_list.html.erb
<h1 class="pb-4 text-3xl">TODOS</h1>

<div>
  <v-todo-lists :todos="<%= @list.to_json %>"></v-todo-lists>
</div>

app/views/pages/todo_list.html.erb
<v-todos></v-todos>

app/views/todo_items/_form.html.erb
<%= form_with(model: todo_item) do |form| %>
  <% if todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
        <% todo_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_field :details %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="field">
    <%= form.label :TodoList_id %>
    <%= form.text_field :TodoList_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<v-todo-item-form :list="<%= @todo_item.to_json %>" form_type="edit"> </v-todo-item-form>

app/views/todo_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th>Completed</th>
      <th>Todolist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.name %></td>
        <td><%= todo_item.details %></td>
        <td><%= todo_item.completed %></td>
        <td><%= todo_item.todo_list_id %></td>
<!--        <td><%#= link_to 'Show', todo_item %></td>-->
<!--        <td><%#= link_to 'Edit', edit_todo_item_path(todo_item) %></td>-->
<!--        <td><%#= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="flex-col inline-flex space-y-3.5 mt-20">
  <v-todo-list :todos="<%= @todo_items.to_json %>"></v-todo-list>
</div>

<%#= link_to 'New Todo Item', new_todo_item_path %>

app/views/todo_items/new.html.erb
<v-todo-list-form :list="<%= @todo_item.to_json %>" form_type="new"> </v-todo-list-form>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo_item.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @todo_item.details %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo_item.completed %>
</p>

<p>
  <strong>Todolist:</strong>
  <%= @todo_item.TodoList_id %>
</p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<v-todo-list-edit
  name="<%= @todo_list.name %>"
  id="<%= @todo_list.id %>"
  message="Todo list edit"
>

</v-todo-list-edit>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<v-todo-lists></v-todo-lists>

app/views/todo_lists/show.html.erb
<v-todo-items :list="<%= @todo_list.to_json %>"></v-todo-items>